server:
  port: 8081
  
spring:
  devtools:
    livereload:
      enabled: false

#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost/chainofmemories
#    username: root
#    password: P@ssw0rd
#    
#  h2:
#    console:
#      enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#      