server:
  port: 18080
  contextPath: /api/v1/
spring:
  devtools:
    livereload:
      enabled: false
  datasource:
    driverClassName: org.postgresql.Driver
    initialSize: 5
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    password: P@ssw0rd
    removeAbandoned: true
    username: postgres
    url: jdbc:postgresql://localhost/postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    io.adrieldg: DEBUG
global:
  clientUrl: http://chainofmemories.dev:8080
security:
  oauth2:
    client:
      clientId: chainofmemories-client
      clientSecret: keyblade
      authorizedGrantTypes: password,refresh_token
      scope: read,write,trust
      id: chainofmemories
      accessTokenValiditySeconds: -1
    resource:
      userInfoUri: /me
