server:
  port: 8081
  
spring:
  devtools:
    livereload:
      enabled: false
      
security:
  oauth2:
    client:
      clientId: chainofmemories-client
      clientSecret: keyblade
      ids: chainofmemories
      authorizedGrantTypes: password,refresh_token
      scopes: read,write,trust
    resource:
      userInfoUri: http://localhost:8081/user 