server:
  port: 18080
  
spring:
  devtools:
    livereload:
      enabled: false
  h2:
    console:
      enabled: true
      path: /console

logging:
  level:
    io.adrieldg: DEBUG

global:
  clientUrl: http://localhost:8080
      
security:
  oauth2:
    client:
      clientId: chainofmemories-client
      clientSecret: keyblade
      authorizedGrantTypes: password,refresh_token
      scope: read,write,trust
      id: chainofmemories
      accessTokenValiditySeconds: -1
    resource:
      userInfoUri: http://localhost:8081/me